### ISSUE TITLE
Updating veency for iOS 11 and above

### ISSUE THREAD

**Issue by subho007** [niknah/veency#10]
Hi Nikiah, I couldn't compile it with iOS11 SDK. It doesn't have most of the framework used to compile. Any changes I should be doing to make this work ?

**Comment by niknah** [comment]
What's the error message?  I haven't done anything with iOS11

**Comment by subho007** [comment]
Attaching the log here, it seems mostly the header files are not found for CoreGraphics, IOSurface and GraphicsSurace. Check the attached log. This used to compile with iOS7 SDK
[error.log](https://github.com/niknah/veency/files/2177954/error.log)

**Comment by subho007** [comment]
This is also relater to this issue - https://github.com/niknah/veency/issues/9

**Comment by niknah** [comment]
There're various arm64 errors there.  The old theos doesn't work for arm64.  Try this new one...

https://github.com/theos/theos

This was made for iOS 7/8 so there's probably a lot other things that need changing.  Sorry, I don't have Xcode or a mac to take a look at it.

Looks like tweak.mm has some re-definitions there, maybe because the headers were missing in the old versions of iOS SDK.  Comment those things out.  IOSurfaceRef, kIOSurfaceIsGlobal, etc...

Some of the things in this repository are precompiled binaries.  They were probably made for 32 bit arm, you may need to re-compile those libvncserver.dylib, etc. if you want to use arm64.

**Comment by subho007** [comment]
Thanks @niknah I will have a look at these and try to recompile them 👍 
Keeping this issue open until I find a way to successfully re-compile veency

**Comment by mileyvirus** [comment]
Hey @subho007 ! If you find a solution to recompile Veency for iOS 11 please share the .deb file or host it on your repo. A lot of people are wishing for it on reddit! ♡

**Comment by subho007** [comment]
@mileyvirus it still doesn't work on iOS 11 even after successful recompilation, give me a week or so to come up with a fix on this 👍

**Comment by DySt4f** [comment]
@subho007 Any news on the iOS 11 ver? I’m really missing it so bad, also thanks for your help!

**Comment by jessesanford** [comment]
Any word on this? I would love to help if possible. What are the current issues?

**Comment by jvyden** [comment]
He's dead.

**Comment by niknah** [comment]
Sorry, I don't have the tools to compile this anymore.  I stopped using it a while ago when they stopped delivering updates to the iPod touch 4th gen, which is what I have.

**Comment by jvyden** [comment]
I have a suitable device, (a touch 6g) as well as a hackintosh. I can probably compile things.

**Comment by niknah** [comment]
Thanks.  There are compile instructions at the bottom of the README page.  But maybe things have changed since it was made with an older version of iOS.

**Comment by Canescj** [comment]
If you guys can get this working I will no lie donate $50 lol

**Comment by subho007** [comment]
Official veency works with unc0ver jailbreak

**Comment by mileyvirus** [comment]
> Official veency works with unc0ver jailbreak

@subho007 could you elaborate on that? [Veency 0.9.3500](https://cydia.saurik.com/info/veency/) or its dependencies put iPhone X 12.1.2 with latest u0 (No RSD) in respring loop. Tried both downloading from Saurik's APT and from your repo at Appknox.

**Comment by bigrck64** [comment]
@subho007 really ? could you tell us what version of iOS and what version of unc0ver are you using to make veency work ?

**Comment by prbreezy** [comment]
Any update on this? I would be very interested to get this works again on iOS 11+.
I think many people will donate (I'm in!)

**Comment by dallasgroot** [comment]
Over a year has passed, any more updates <3

**Comment by bigrck64** [comment]
There is a iOS11 working version of veency here now :)
https://github.com/cosmosgenius/screendump/releases

Next challenge is to make it works with iOS12 / 13.
